#!/usr/bin/env php
<?php

use Verraes\UpToDocs\Main;

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        require $file;
        exit(Main::main());
    }
}

echo "Can't find autoload. Did you run composer install?";
exit(1);