#!/usr/bin/env php
<?php

use Verraes\UpToDocs\Main;

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
} elseif(file_exists(__DIR__ . '/../../vendor/autoload.php')) {
    require_once __DIR__ . '/../../vendor/autoload.php';
} else {
    throw new \Exception("Cound't find autoloader");
}

Main::main();